title: Xinpan Yuan's Homepage
page-top-title: Xinpan Yuan | 袁鑫攀
top-section-bg-text: 致良知
home-subtitle: Xinpan Yuan &ensp;|&ensp;袁鑫攀
copyright-text: '&copy; Xinpan Yuan  2023-2025. All Rights Reserved.'
